export const INIT_HOME_STATE = 'INIT_HOME_STATE'
export const INIT_SHOP_STATE = 'INIT_SHOP_STATE'
export const INIT_STOCK_STATE = 'INIT_STOCK_STATE'
export const INIT_USER_STATE = 'INIT_USER_STATE'

export const YS_GET_PHONE_LOGIN = 'YS_GET_PHONE_LOGIN'
export const CHANGE_TAB_VALUE = 'CHANGE_TAB_VALUE'
export const GET_USER_SHOP_LIST = 'GET_USER_SHOP_LIST'
export const YS_CHANGE_USER_INFO = 'YS_CHANGE_USER_INFO'
export const YS_GET_SHOP_INFO = 'YS_GET_SHOP_INFO'

export const CHANGE_PAGE_CONTENT_IS_MODIFY = 'CHANGE_PAGE_CONTENT_IS_MODIFY'
export const CHANGE_KEY_BOARD_SHOW = 'CHANGE_KEY_BOARD_SHOW'

export const YS_SYSTEM_INFO = 'YS_SYSTEM_INFO'