
export const INIT_USER_STATE = 'INIT_USER_STATE'
export const INIT_SHOP_STATUS_FOR_USER = 'INIT_SHOP_STATUS_FOR_USER'
export const YS_GET_ADMIN_INFO = 'YS_GET_ADMIN_INFO'
export const YS_GET_SHOP_LIST = 'YS_GET_SHOP_LIST'
export const YS_GET_SHOP_INFO = 'YS_GET_SHOP_INFO'
export const YS_CHANGE_USER_INFO = 'YS_CHANGE_USER_INFO'

export const INIT_SHOP_STATUS_FOR_SHOP = 'INIT_SHOP_STATUS_FOR_SHOP'
export const INIT_SHOP_STATUS_FOR_STOCK = 'INIT_SHOP_STATUS_FOR_STOCK'